# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee21c6706b1cd067d4f2654adadfdec4ffca450b481830bbe6697a672418cf47753fe4d840aae5e36358da97ed23fca7141b77c1900e2ebcc9e8121f82a5d842

test:
  secret_key_base: 38b3e7c3e685c3d35fcede090029a0ad4cbf04ebd6c36197076e6416f6b97e0b11db5e014cde8ca39bb093225bc58dbfe53cb580e50afc00c112703e85f4c361

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
